.TH "algorithms.h" 3 "Sun Oct 19 2014" "MiOIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
algorithms.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBrandomAlg\fP ()"
.br
.ti -1c
.RI "void \fBheuristicAlg\fP ()"
.br
.ti -1c
.RI "void \fBgreedyAlg\fP ()"
.br
.ti -1c
.RI "void \fBsteepesAlg\fP ()"
.br
.ti -1c
.RI "void \fBprintResults\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void greedyAlg ()"

.SS "void heuristicAlg ()"

.SS "void printResults ()"

.SS "void randomAlg ()"

.SS "void steepesAlg ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for MiOIB from the source code\&.
