.TH "lab_jacek.cpp" 3 "Sun Oct 19 2014" "MiOIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lab_jacek.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <memory\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBfactorial\fP (unsigned int n)"
.br
.ti -1c
.RI "void \fBswapElements\fP (int **perm, int permNumber, int posElemA, int posElemB)"
.br
.ti -1c
.RI "int ** \fBinitializeAllNeighbours\fP (int length, int *input)"
.br
.ti -1c
.RI "void \fBprintAllNeighbours\fP (int **permutations, int length)"
.br
.ti -1c
.RI "void \fBclearArrays\fP (int **permutations, int length)"
.br
.ti -1c
.RI "int \fBold_main\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void clearArrays (int **permutations, intlength)"

.SS "int factorial (unsigned intn)\fC [inline]\fP"

.SS "int** initializeAllNeighbours (intlength, int *input)"

.SS "int old_main ()"

.SS "void printAllNeighbours (int **permutations, intlength)"

.SS "void swapElements (int **perm, intpermNumber, intposElemA, intposElemB)"

.SH "Author"
.PP 
Generated automatically by Doxygen for MiOIB from the source code\&.
