.TH "main.cpp" 3 "Sun Oct 19 2014" "MiOIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/algorithms\&.h'\fP
.br
\fC#include '\&.\&./inc/instances\&.h'\fP
.br
\fC#include '\&.\&./inc/measures\&.h'\fP
.br
\fC#include '\&.\&./inc/operations\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int * \fBsolution\fP"
.br
.ti -1c
.RI "int ** \fBneighbours\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Variable Documentation"
.PP 
.SS "int** neighbours"

.SS "int* solution"

.SH "Author"
.PP 
Generated automatically by Doxygen for MiOIB from the source code\&.
