.TH "measures.cpp" 3 "Sun Oct 19 2014" "MiOIB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
measures.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/measures\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBrateSolution\fP (int **A, int **B, int *\fBsolution\fP, unsigned int \fBsz\fP)"
.br
.ti -1c
.RI "int \fBrateChange\fP (int **A, int **B, int *\fBsolution\fP, unsigned int \fBsz\fP, unsigned int pos1, unsigned int pos2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int rateChange (int **A, int **B, int *solution, unsigned intsz, unsigned intpos1, unsigned intpos2)"
Returns the difference in cost function if elements on positions pos1 and pos2 switch places in given solution vector\&. It makes $8n$ multiplications\&. 
.PP
\fBParameters:\fP
.RS 4
\fIA\fP Matrix with flow values between facilities\&. 
.br
\fIB\fP Matrix with distance values between locations\&. 
.br
\fIsolution\fP Pointer to the \fBoriginal\fP (i\&.e\&. previous) solution (array of ints)\&. 
.br
\fIsz\fP Size of the problem and solution\&. 
.br
\fIpos1\fP Position of the first element to be swapped\&. 
.br
\fIpos2\fP Position of the second element to be swapped\&. 
.RE
.PP

.SS "int rateSolution (int **A, int **B, int *solution, unsigned intsz)"
Returns the cost for given solution vector\&. It makes $n^2$ multiplications\&. 
.PP
\fBParameters:\fP
.RS 4
\fIA\fP Matrix with flow values between facilities\&. 
.br
\fIB\fP Matrix with distance values between locations\&. 
.br
\fIsolution\fP Pointer to the solution (array of ints)\&. 
.br
\fIsz\fP Size of the problem and solution\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Integer value with cost\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MiOIB from the source code\&.
